language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
install: ".travis/install-pack.sh"
script: make test build acceptance
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/deploy.sh
  on:
    all_branches: true
    condition: "$TRAVIS_EVENT_TYPE = push && ($TRAVIS_BRANCH = master || $TRAVIS_BRANCH
      =~ ^v([0-9]+\\.)+x$)"
notifications:
  slack:
    secure: V2PIOLhkKd+u8YKr6i6BWxmVUgyH/fvSCt78ydQCg8f7YLbrSQhpaatKW2AOoRaJxuIOXC1fzNo/S5iAuj1DnY77OuVMocCFxjFqvzjnebfX33A9D7sVAnw2JEb7Hwwj00x79nsKaG/mmzWOvg39d1qWgdXqy51GQP1DocdEo3StUA99yOUYo5GtZGBBYZ6wq+vn43TamOH6xIjn/NB6QtEEJKXxZwuy8AEnCfMhc6m6FvXXIWy8Qb6SqhB7RZAV8FhxOo5xRtwrhJbZuPWRP+V9WueQ9jsALNMWGBg4wAOLMCb5pIkVkRaw3nEsWiZThd4Z2FbJAE8i9rhz8U+Na90AmB9kQHgYbOAGF9Fu1uz1S9CWy1npTdGOGNLGocsow6roF9gll9UVk7r+XBwjEBY6Kr2nXBaNuXaL+d0+MVo4TGxtR8Ctdiff/TADO4ltSWXtt4VphpK6hg7na2LezfFqOUJAPV26E4Huw+JEcTQl2lAzjZJ+E31ZLTn2rIWeZneejWLjWAl1b1D1Fx5IxjM8UM0VaruMLWKgj9491bEDY5x4+hZIFg80l5wD/+OGFmz3LdPUhdtfI1l9k23BEHfYqfIhtOfA8xqusmBGexRUrMnxvy8myNOpAcl/OsO7YGV8WF+BwcCSIcvf3d//86gVEpNCX9R0fySdytCmRDg=
