---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
- name: riff-buildpack

outputs:
- name: artifactory

caches:
- path: go-module-cache

run:
  path: riff-buildpack/ci/package.sh
